<a href="https://colab.research.google.com/github/Yupipapuu/Trabajos-THC/blob/main/29_10_2024_THC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])#arreglo
print(type(a))
<class 'numpy.array'>
print(a)
[1 2 3 4]

SyntaxError: invalid syntax (<ipython-input-7-6fb54b6fe39a>, line 3)

In [8]:
arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
A=np.array([[1/2,2,3/4],[0,1,0],[2,4,5]])
print(A)

[[0.5  2.   0.75]
 [0.   1.   0.  ]
 [2.   4.   5.  ]]


In [4]:
import numpy as np
A=np.array([[1,'0'],[0,0]])
print(A)

[['1' '0']
 ['0' '0']]


In [16]:
Vec=np.array([2,0,-1,4,5,6,7,8,9,10])
print(Vec)
print(Vec[1:4])
print(Vec[2:5])
print(Vec[1:10:2])

[ 2  0 -1  4  5  6  7  8  9 10]
[ 0 -1  4]
[-1  4  5]
[ 0  4  6  8 10]


In [32]:
Mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#Acceder al 2
Mat[0,1]
Mat[2,2]
Mat[1,3]
Mat[-1,-1]
Mat[:,1]
Mat[1,1:4]
Mat[1:3,2]
Mat[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [35]:
Mat[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [36]:
Mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
Mat+Mat

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

suma = a + b
print("Suma de a y b:", suma)

producto_punto = np.dot(a, b)
print("Producto punto de a y b:", producto_punto)

n = len(a)  # n = 4
for i in range(n):
    print(f"Elemento {i} de a * Elemento {i} de b: {a[i] * b[i]}")


Suma de a y b: [ 5  7  9 11]
Producto punto de a y b: 60
Elemento 0 de a * Elemento 0 de b: 4
Elemento 1 de a * Elemento 1 de b: 10
Elemento 2 de a * Elemento 2 de b: 18
Elemento 3 de a * Elemento 3 de b: 28
